name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      # - name: Install Newman
      #   run: |
      #     npm install -g newman
      #     npm install -g newman-reporter-htmlextra

      # - name: Generate and Upload Report
      #   run: |

      #     newman run "Collections/Cricket_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Cricket_Bet_Flow_Matched-report.html || true

      #     newman run "Collections/Cricket_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Cricket_Bet_Flow_Unmatched-report.html || true

      #     newman run "Collections/RESTful_API_Basics.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/RESTful_API_Basics-report.html || true

      #     newman run "Collections/Soccer_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Soccer_Bet_Flow_Matched-report.html || true

      #     newman run "Collections/Soccer_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Soccer_Bet_Flow_Unmatched-report.html || true

      #     newman run "Collections/Tennis_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Tennis_Bet_Flow_Matched-report.html || true

      #     newman run "Collections/Tennis_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/Tennis_Bet_Flow_Unmatched-report.html || true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
  
      - name: Install k6
        run: |
          wget -O k6 https://github.com/k6io/k6/releases/latest/download/k6-linux-amd64
          chmod +x k6
          sudo mv k6 /usr/local/bin/


      - name: Generate and Upload Report
        run: |
          k6 run Collections/Cricket_Bet_Flow_Matched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Cricket_Bet_Flow_Matched-report.json
          k6 run Collections/Cricket_Bet_Flow_Unmatched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Cricket_Bet_Flow_Unmatched-report.json
          k6 run Collections/RESTful_API_Basics.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/RESTful_API_Basics-report.json
          k6 run Collections/Soccer_Bet_Flow_Matched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Soccer_Bet_Flow_Matched-report.json
          k6 run Collections/Soccer_Bet_Flow_Unmatched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Soccer_Bet_Flow_Unmatched-report.json
          k6 run Collections/Tennis_Bet_Flow_Matched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Tennis_Bet_Flow_Matched-report.json
          k6 run Collections/Tennis_Bet_Flow_Unmatched.js --env=Env/PlayEnv.postman_environment.json --out json=SampleArtifact/Tennis_Bet_Flow_Unmatched-report.json

      - name: Publish Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: SampleArtifact

