name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Generate and Upload Report
        run: |

          newman run "Collections/Cricket_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/Cricket_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/RESTful_API_Basics.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/Soccer_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/Soccer_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/Tennis_Bet_Flow_Matched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

          newman run "Collections/Tennis_Bet_Flow_Unmatched.postman_collection.json" -e "Env/PlayEnv.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

      - name: Publish Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: SampleArtifact

