name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: list contents
        run: |
          ls

      - name: Generate and Upload Report
        run: |
          newman run "Cricket_Bet_Flow_Matched.postman_collection1.json" --reporters cli,htmlextra --reporter-htmlextra-export SampleArtifact/newman-report.html || true

      - name: Publish Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: SampleArtifact

