name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMANAPI_SECRET }}
          collection: Cricket_Bet_Flow_Matched.postman_collection.json
          environment: 22939286-f59f94ad-afe0-4adf-96a6-71d5c1f00da9
        continue-on-error: true

      - name: list contents
        run: |
          ls

      - name: Publish Report
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: SampleArtifact

