name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # - uses: actions/checkout@v3
    # - name: Create directory
    #   run:
    #     mkdir SampleArtifact

    # - name: Install Node
    #   uses: actions/checkout@v3
    #   with:
    #     node-version : "17.x"

    # - name: Install Newman
    #   run: |
    #     npm install -g newman
    #     npm install -g newman-reporter-htmlextra

    # - name: Run Collection
    #   run: |
    #     ls
    #     newman run "Cricket_Bet_Flow_Matched.postman_collection.json"

    # - name: Publish Report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Reports
    #     path: SampleArtifact

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: "PMAK-64702cfa76de510a67124f55-b6a5c77fa2eb50078886753952fec1eca9"
          collection: Cricket_Bet_Flow_Matched
          environment: 22939286-f59f94ad-afe0-4adf-96a6-71d5c1f00da9

