name: postman-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # - uses: actions/checkout@v3
    # - name: Create directory
    #   run:
    #     mkdir SampleArtifact

    # - name: Install Node
    #   uses: actions/checkout@v3
    #   with:
    #     node-version : "17.x"

    # - name: Install Newman
    #   run: |
    #     npm install -g newman
    #     npm install -g newman-reporter-htmlextra

    # - name: Run Collection
    #   run: |
    #     ls
    #     newman run "Cricket_Bet_Flow_Matched.postman_collection.json"

    # - name: Publish Report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Reports
    #     path: SampleArtifact

      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: "PMAK-646e00db596ece2e145702f2-3a119dc11746a6c16ac80319059905cb0e"
          collection: Cricket_Bet_Flow_Matched.postman_collection.json
          environment: 22939286-716465fd-0e15-4434-a292-98d0face0105
